# -*- coding: utf-8 -*-
"""Minor Project 1 (Priyanuj Kalita).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMGWjrpP1Zj-sS2r2FU5KAe9kgYo65fQ

# Student Marks Analyzer
"""

# Importing necessary libraries.

import numpy as np

# Starting an array of student marks

marks_arr = np.array([])

# Taking marks from students (assuming there are 5 subject marks to analyze)

for i in range(5):

    marks_str = input(f"Subject {i + 1} Marks: ")
    marks = int(marks_str)

    # checking if the marks are valid

    if marks < 0:

      print("Invalid Marks")
      break

    elif marks > 100:

      print("Invalid Marks")
      break

    # Adding the marks in the NumPy array

    marks_arr = np.append(marks_arr, marks)

print("Your Final Marks List: ", marks_arr)

# Now, finding total, average, highest and lowest marks.

total = np.sum(marks_arr)
average = np.mean(marks_arr)
highest = np.max(marks_arr)
lowest = np.min(marks_arr)

print("Total Marks: ", total)
print("Average Marks: ", average)
print("Highest Marks: ", highest)
print("Lowest Marks: ", lowest)

# Grading the student

if average > 85:
  print("Grade: A")

elif average >= 70 and average <= 85:
  print("Grade: B")

elif average >= 50 and average <= 69:
  print("Grade: C")

else:
  print("Failed")